### ISSUE TITLE
Failing front-end tests

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/tech-test-joao#11]
Some of your front end tests are failing! 
![Screen Shot 2019-11-15 at 12 32 47](https://user-images.githubusercontent.com/37771591/68943778-0cdc0c00-07a4-11ea-879f-ad4b3157cfbe.png)

Also, in regards to front-end tests - can you create a few integration tests that mock user input so that we can see how components work with eachother?

**Comment by Joaoviana** [comment]
thank you for pointing that out, I have just updated the `master` branch.

please run `npm i` again

please find tests here: 
https://github.com/FACxBeamery/tech-test-joao/blob/master/client/src/components/Form/Form.test.js
https://github.com/FACxBeamery/tech-test-joao/blob/master/client/src/components/JobList/JobCardWrapper.test.js

**Comment by teenie-quaggard** [comment]
Still some errors on my end!
![Screen Shot 2019-11-15 at 13 23 53](https://user-images.githubusercontent.com/37771591/68946661-6c89e580-07ab-11ea-97e2-5840253cfda0.png)
